# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "neb-science-hub"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size
# for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[studio]
# Port to use for Supabase Studio.
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
# Port to use for the email testing server web interface.
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000", "https://neb-science-hub.vercel.app"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 seconds (1
# week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = true

# Configure OAuth providers
[auth.external.apple]
enabled = true
client_id = ""
secret = ""
redirect_uri = ""
# Overrides the default auth redirectUrl.
url_override = ""

[auth.external.google]
enabled = true
client_id = ""
secret = ""
redirect_uri = ""
# Overrides the default auth redirectUrl.
url_override = ""

# Email auth provider is enabled by default. To disable it, set `enable` to `false`.
[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = true
# If enabled, users will be able to reset their passwords.
enable_password_recovery = true

# Use an automatic template for emails.
[auth.email.template]
# Change the current templates to your own.
enable_email_templates = true
# Configure the email template colors and other styling attributes.
template_config.colors.button.text = "#1a1a1a"
template_config.colors.button.background = "#fde68a"
template_config.colors.body_text = "#4b5563"
template_config.colors.link_text = "#6366f1"
template_config.colors.background = "#ffffff"

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Configure analytics providers

[functions]
[functions.handle-contact]
verify_jwt = false
[functions.handle-subscription]
verify_jwt = false
