
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use hardcoded values for now since .env variables aren't loading correctly
const SUPABASE_URL = 'https://laurvehulnkfxmmdbodf.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhdXJ2ZWh1bG5rZnhtbWRib2RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTc4MzksImV4cCI6MjA2MDM5MzgzOX0.KLrec4Pj-cfkApLNCXcS-iuNxtmudzrURSy2r8maxEI';

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error(
    'Missing Supabase credentials. Using hardcoded values is not recommended for production.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});
